matrix:
  include:
  - os: linux
    language: java
    jdk: oraclejdk8
    env:
      KBUILD=linux
      JAVA_OPTS=-Xmx2g
    script:
    - ./gradlew -s -i check build
  - os: linux
    language: java
    jdk: oraclejdk8
    env:
      KBUILD=chrome
      JAVA_OPTS=-Xmx2g
    script:
      - ./gradlew -s -i jsTestChrome
  - os: windows
    env: KBUILD=windows
    language: shell # java is not supported but jdk is installed
    script:
    - powershell -Command "cmd /c travis_win.bat"
  - os: osx
    env:
      KBUILD=macos
      JAVA_OPTS=-Xmx2g
    language: java
    jdk: openjdk10
    before_install:
    - cp $(/usr/libexec/java_home)/lib/security/cacerts "${JAVA_HOME}/lib/security/cacerts"
    script:
    - ./gradlew -s -i check build
  - os: linux
    language: android
    android:
      components:
        - build-tools-28.0.3
        - android-28
    jdk: oraclejdk8
    env:
      KBUILD=android
      JAVA_OPTS=-Xmx2g
    script:
      - ./gradlew -s -i check build

