language: java

jdk:
  - oraclejdk8

install:
  - nvm install 8
  - nvm use 8
  - node --version
  - npm -g install mocha
  - which node
  - which mocha

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew -s -i check install

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
