[versions]
jackson-databind = "2.14.2"
jackson-module-kotlin = "2.14.2"
jna = "5.13.0"
jcodec = "0.2.5"
junit = "4.13.2"
proguard-gradle = "7.2.2"

kotlin = "1.9.0"
kotlinx-coroutines = "1.7.2"
kotlinx-atomicfu = "0.21.0"
kotlinx-serialization = "1.5.1"

#maven { url = uri("https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev") }

# https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/org/jetbrains/kotlin/kotlin-stdlib/
#kotlin = "1.9.0-dev-6976"
#kotlin = "1.9.20-dev-2332"
#kotlin = "1.9.20-dev-2914"
# https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental/org/jetbrains/kotlinx/atomicfu/
#kotlinx-atomicfu = "0.20.2-wasm0"
# https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental/org/jetbrains/kotlinx/kotlinx-coroutines-core/
#kotlinx-coroutines = "1.7.0-RC-wasm0"
#kotlinx-serialization = "1.5.1-wasm0"

kotlinx-benchmark = "0.4.7"
dokka = "1.8.10"
kover = "0.6.1"
kover-agent = "1.0.712"
node = "16.9.1"
android-build-gradle = "7.3.1"
gson = "2.10.1"
gradle-publish-plugin = "1.1.0"
closure-compiler = "v20210808"
# https://repo.maven.apache.org/maven2/org/jetbrains/intellij/deps/intellij-coverage-agent/

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-module-kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kover = { module = "org.jetbrains.kotlinx:kover", version.ref = "kover" }
kover-intellij-agent = { module = "org.jetbrains.intellij.deps:intellij-coverage-agent", version.ref = "kover-agent" }
jna-core = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jcodec-core = { module = "org.jcodec:jcodec", version.ref = "jcodec" }
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard-gradle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-build-gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gradle-publish-plugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradle-publish-plugin" }
closure-compiler = { module = "com.google.javascript:closure-compiler", version.ref = "closure-compiler" }

[bundles]
jna = ["jna-core", "jna-platform"]
kotlinx-coroutines = ["kotlinx-coroutines-core", "kotlinx-atomicfu"]

#[plugins]
#jmh = { id = "me.champeau.jmh", version = "0.6.5" }
