[versions]
jna = "5.13.0"
jcodec = "0.2.5"
proguard-gradle = "7.2.2"
#kotlin = "1.8.10"
#kotlin = "1.8.255-SNAPSHOT"
kotlin = "1.9.255-SNAPSHOT"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.5.0-RC"
kotlinx-atomicfu = "0.19.0"
kotlinx-benchmark = "0.4.7"
dokka = "1.7.20"
kover = "0.6.1"
kover-agent = "1.0.692"
node = "16.9.1"
android-build-gradle-java8 = "4.2.0"
android-build-gradle-java11 = "7.0.4"
gson = "2.8.6"
#gradle-publish-plugin = "1.0.0"
gradle-publish-plugin = "0.14.0"
closure-compiler = "v20210808"
# https://repo.maven.apache.org/maven2/org/jetbrains/intellij/deps/intellij-coverage-agent/

[libraries]
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kover = { module = "org.jetbrains.kotlinx:kover", version.ref = "kover" }
kover-intellij-agent = { module = "org.jetbrains.intellij.deps:intellij-coverage-agent", version.ref = "kover-agent" }
jna-core = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jcodec-core = { module = "org.jcodec:jcodec", version.ref = "jcodec" }
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard-gradle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
android-build-gradle-java8 = { module = "com.android.tools.build:gradle", version.ref = "android-build-gradle-java8" }
android-build-gradle-java11 = { module = "com.android.tools.build:gradle", version.ref = "android-build-gradle-java11" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gradle-publish-plugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradle-publish-plugin" }
closure-compiler = { module = "com.google.javascript:closure-compiler", version.ref = "closure-compiler" }

[bundles]
jna = ["jna-core", "jna-platform"]

#[plugins]
#jmh = { id = "me.champeau.jmh", version = "0.6.5" }
