[versions]
jna = "5.11.0"
jcodec = "0.2.5"
proguard-gradle = "7.2.2"
kotlin = "1.7.10"
kotlinx-coroutines = "1.6.3"
kotlinx-serialization = "1.3.2"
node = "16.9.1"
android-build-gradle = "7.0.3"
gson = "2.8.6"
gradle-publish-plugin = "0.14.0"
closure-compiler = "v20210808"

# https://androidx.dev/storage/compose-compiler/repository
# https://github.com/JetBrains/compose-jb/issues/2108#issuecomment-1157978869
kotlinx-compose = "1.2.0-alpha01-dev748"
androidx-compose-compiler = "1.2.0-alpha01-dev748"

[libraries]
jna-core = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
jcodec-core = { module = "org.jcodec:jcodec", version.ref = "jcodec" }
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard-gradle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-compose-gradle-plugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "kotlinx-compose" }
kotlinx-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "kotlinx-compose" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-build-gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
gradle-publish-plugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradle-publish-plugin" }
closure-compiler = { module = "com.google.javascript:closure-compiler", version.ref = "closure-compiler" }

[bundles]
jna = ["jna-core", "jna-platform"]

#[plugins]

#jmh = { id = "me.champeau.jmh", version = "0.6.5" }
